[project]
name = "py-model"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Justus Kilian Wolff", email = "moin@justuskilianwolff.com" },
]
requires-python = ">=3.11.9"
dependencies = []

[project.scripts]
py-model = "py_model:main"

[dependency-groups]
dev = [
    "coverage>=7.10.7",
    "ipython>=9.6.0",
    "pylint>=4.0.0",
    "pytest>=8.4.2",
    "python-dotenv>=1.1.1",
    "ruff>=0.14.0",
    "vulture>=2.14",
]

[build-system]
requires = ["uv_build>=0.9.2,<0.10.0"]
build-backend = "uv_build"

[tool.ruff]
line-length = 120
respect-gitignore = false
src = ["src"]
extend-include = ["*.ipynb"]
exclude = [".venv"]

[tool.ruff.lint]
extend-select = ["I"] # also sort imports etc

[tool.pytest.ini_options]
log_cli = true
log_cli_level = "WARNING"
addopts = "-W ignore::DeprecationWarning"

[tool.pylint]
disable = [
    "C0103", # constants not upper case
    "C0301", # line too long
    "C0114", # missing module docstring
    "W1203", # logger with f string formatting
    "R0913", # too many arguments
    "W0511", # fixme
    "W0212", # accessing protected members
    "R1720", # Unnecessary "elif" after "raise", remove the leading "el" from "elif" (has a better readibility though)
    "R0914", # too many local variables
    "R1705", # else after return (improves readibility imho)
    "R0902", # too many instance attributes
    "R0903", # too few public methods
]
ignore-paths = [".venv", "test[^_]*py"]
recursive = "y"

[tool.vulture]
exclude = [".venv", "tests"]
min_confidence = 100
paths = ["."]
ignore_decorators = ["@vulture_ignore"]

[tool.coverage.run]
source = ["src"]
